
DATABASE = './db/app.db'

VERSION = 'v1'
SUB_URL = f'/{VERSION}/app'

PREFIX_APP01 = 'app01'
TABLE_NAME_APP01 = 'APP01'
CREATE_DB_APP01 = f'''CREATE TABLE IF NOT EXISTS {TABLE_NAME_APP01}(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT UNIQUE NOT NULL,
PASSWD TEXT NOT NULL);'''

PREFIX_APP02 = 'app02'
TABLE_NAME_APP02 = 'APP02'
CREATE_DB_APP02 = f'''CREATE TABLE IF NOT EXISTS {TABLE_NAME_APP02}(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT UNIQUE NOT NULL,
PASSWD TEXT NOT NULL);'''
